"""Generate the Azure topology diagram as Mermaid.

Queries Azure Resource Graph across every active tenant in
config/tenants.yaml and emits a ``flowchart TB`` that renders:

    Management Groups → Subscriptions → Resource Groups → resource-type counts

Tag-based callouts highlight:
    - env=prod        (bordered node)
    - riverside=true  (tinted node)

The Mermaid text is the canonical artefact — the drawio/SVG exports
produced by `.github/workflows/topology-export.yml` are derived from it.

Offline mode (``--offline`` or no credentials available) emits a
placeholder diagram so the repo always has a renderable
``docs/diagrams/topology.mmd``.
"""

from __future__ import annotations

import argparse
import logging
import sys
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
DIAGRAM_PATH = REPO_ROOT / "docs" / "diagrams" / "topology.mmd"
logger = logging.getLogger("topology")

# KQL queries — minimal columns, single request per query type.
KQL_CONTAINERS = (
    "ResourceContainers "
    "| where type in~ ("
    "'microsoft.management/managementgroups',"
    "'microsoft.resources/subscriptions',"
    "'microsoft.resources/subscriptions/resourcegroups'"
    ") "
    "| project id, name, type, tenantId, subscriptionId, properties, tags"
)
KQL_RESOURCE_COUNTS = (
    "Resources "
    "| summarize count=count() by subscriptionId, resourceGroup, type "
    "| project subscriptionId, resourceGroup, type, count"
)


def _load_tenants() -> list[dict[str, Any]]:
    import yaml

    for name in ("tenants.yaml", "tenants.yaml.example"):
        path = REPO_ROOT / "config" / name
        if path.exists():
            raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
            return [
                {"code": code, **(cfg or {})}
                for code, cfg in (raw.get("tenants") or {}).items()
                if (cfg or {}).get("is_active", True)
            ]
    return []


def _safe_id(value: str) -> str:
    """Mermaid-safe node id."""
    out = []
    for ch in value or "":
        out.append(ch if ch.isalnum() else "_")
    return "n_" + "".join(out)[-60:]


def _query_graph(tenants: list[dict[str, Any]]) -> dict[str, Any] | None:
    """Run the KQL queries via Azure Resource Graph. Returns None on failure."""
    try:
        from azure.mgmt.resourcegraph import ResourceGraphClient
        from azure.mgmt.resourcegraph.models import QueryRequest

        from app.core.oidc_credential import get_oidc_provider
    except Exception as exc:
        logger.warning("azure-mgmt-resourcegraph not available: %s", exc)
        return None

    provider = get_oidc_provider()
    containers: list[dict[str, Any]] = []
    counts: list[dict[str, Any]] = []
    for t in tenants:
        tenant_id = t.get("tenant_id")
        app_id = t.get("multi_tenant_app_id") or t.get("app_id")
        if not tenant_id or not app_id:
            continue
        try:
            credential = provider.get_credential_for_tenant(tenant_id, app_id)
            client = ResourceGraphClient(credential)
            for query, bucket in ((KQL_CONTAINERS, containers), (KQL_RESOURCE_COUNTS, counts)):
                resp = client.resources(QueryRequest(query=query, subscriptions=None))
                if resp and resp.data:
                    bucket.extend(resp.data)
        except Exception as exc:
            logger.warning("resource-graph query failed for %s: %s", t.get("code"), exc)
            continue

    return {"containers": containers, "counts": counts}


def _render_mermaid(data: dict[str, Any] | None) -> str:
    """Render the Mermaid flowchart. Handles the offline/empty case."""
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    header = [
        f"%% Azure topology — generated {now}",
        "%% Regenerated by scripts/generate_topology.py on every push.",
        "%% DO NOT hand-edit — changes will be overwritten.",
        "flowchart TB",
        "  classDef prod stroke:#ef4444,stroke-width:2px;",
        "  classDef riverside fill:#f0abfc,stroke:#86198f,color:#3b0764;",
        "  classDef mg fill:#e0e7ff,stroke:#4338ca,color:#1e1b4b;",
        "  classDef sub fill:#dcfce7,stroke:#15803d,color:#052e16;",
        "  classDef rg fill:#fef3c7,stroke:#b45309,color:#451a03;",
        "  classDef res fill:#f1f5f9,stroke:#475569,color:#0f172a;",
    ]
    if not data or (not data["containers"] and not data["counts"]):
        header.append(
            '  placeholder["No Azure data available — run the workflow with OIDC credentials."]'
        )
        return "\n".join(header) + "\n"

    # Index by type.
    mgs: dict[str, dict[str, Any]] = {}
    subs: dict[str, dict[str, Any]] = {}
    rgs: dict[str, dict[str, Any]] = {}
    for row in data["containers"]:
        t = (row.get("type") or "").lower()
        if "managementgroups" in t:
            mgs[row["id"]] = row
        elif t.endswith("subscriptions"):
            subs[row.get("subscriptionId") or row.get("id")] = row
        elif "resourcegroups" in t:
            key = f"{row.get('subscriptionId')}::{row.get('name')}"
            rgs[key] = row

    # Aggregate resource counts.
    by_rg: dict[str, list[tuple[str, int]]] = defaultdict(list)
    for c in data["counts"]:
        key = f"{c.get('subscriptionId')}::{c.get('resourceGroup')}"
        by_rg[key].append((c.get("type", "unknown"), int(c.get("count", 0))))

    # Parent lookups.
    parent_of_sub: dict[str, str] = {}
    for row in data["containers"]:
        props = row.get("properties") or {}
        management_group = props.get("managementGroupId") or props.get("parent") or {}
        if isinstance(management_group, dict):
            management_group = management_group.get("id", "")
        if (row.get("type") or "").lower().endswith("subscriptions"):
            parent_of_sub[row.get("subscriptionId") or row.get("id")] = management_group

    out: list[str] = list(header)

    # Render MGs
    for mg_id, mg in mgs.items():
        nid = _safe_id(mg_id)
        label = mg.get("name", "mg")
        out.append(f'  {nid}["MG: {label}"]:::mg')

    # Subs
    for sub_id, sub in subs.items():
        nid = _safe_id(sub_id)
        label = sub.get("name") or sub_id[:8]
        tags = sub.get("tags") or {}
        cls = "sub"
        if str(tags.get("riverside", "")).lower() == "true":
            cls = "sub,riverside"
        out.append(f'  {nid}["Sub: {label}"]:::{cls}')
        parent = parent_of_sub.get(sub_id)
        if parent and parent in mgs:
            out.append(f"  {_safe_id(parent)} --> {nid}")

    # RGs
    for key, rg in rgs.items():
        nid = _safe_id(key)
        label = rg.get("name", "rg")
        tags = rg.get("tags") or {}
        cls = "rg"
        if str(tags.get("env", "")).lower() == "prod":
            cls = "rg,prod"
        if str(tags.get("riverside", "")).lower() == "true":
            cls = cls + ",riverside"
        out.append(f'  {nid}["RG: {label}"]:::{cls}')
        sub_nid = _safe_id(rg.get("subscriptionId") or "")
        out.append(f"  {sub_nid} --> {nid}")

        # Resource-type rollups under the RG.
        for res_type, count in sorted(by_rg.get(key, []), key=lambda x: -x[1])[:8]:
            res_short = res_type.split("/")[-1]
            res_nid = _safe_id(f"{key}::{res_type}")
            out.append(f'  {res_nid}["{res_short} × {count}"]:::res')
            out.append(f"  {nid} --> {res_nid}")

    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate the Azure topology Mermaid diagram.")
    p.add_argument("--output", default=str(DIAGRAM_PATH), help="Path to the .mmd output file.")
    p.add_argument("--offline", action="store_true", help="Skip Azure calls, emit a placeholder.")
    p.add_argument("-v", "--verbose", action="store_true")
    args = p.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    sys.path.insert(0, str(REPO_ROOT))

    tenants = _load_tenants()
    if args.offline or not tenants:
        data: dict[str, Any] | None = None
    else:
        data = _query_graph(tenants)

    mermaid = _render_mermaid(data)
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(mermaid, encoding="utf-8")
    logger.info("topology: wrote %d bytes to %s", len(mermaid), out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
